# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'
use_frameworks!

target "FrickImpactAcademy" do
pod 'SwiftInstagram', '~> 1.1.1'

#pod 'Firebase/Core'
#pod 'Firebase/Database'
#pod 'Mixpanel-swift'



end 

